# Generated by Django 2.1 on 2020-12-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_app',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(default=None, max_length=255)),
                ('quantity', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseStatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase_app')),
            ],
            options={
                'verbose_name': 'Purchase Status',
                'verbose_name_plural': 'Purchases Status',
                'db_table': 'purchase_status',
            },
        ),
    ]
