# Generated by Django 2.1 on 2020-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatusmodel',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
